### ISSUE TITLE
Add additional test cases

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent-integration-tests#3]
More a _note to self_ so that I don't forget what I just thought about while reviewing:
- Test repository with illegal url 
- Test repository with illegal/differing type

This should wait for any discussions about our package handling

**Comment by siegfriedweber** [comment]
> - Test repository with illegal url

Meanwhile, repositories without an URL and an unreachable URL are already tested.
https://github.com/stackabletech/agent-integration-tests/blob/9ad6653e87279c06fec2b6b4426941c38c4a4507/tests/repository.rs#L24-L55

> - Test repository with illegal/differing type

The integration tests expect a running Stackable Agent. The Stackable Agent starts only with an existing resource definition for Stackable repositories. The CRD provided by the Stackable Agent enforces the type `StackableRepo`. In this situation, an integration test cannot create a repository with another type. It would be possible within the integration test to delete the existing CRD and apply a CRD which allows an illegal repository type. In my opinion, this situation would be too contrived and is not worth to be tested.

@soenkeliebau I vote to close this issue.

**Comment by soenkeliebau** [comment]
fine for me
