### ISSUE TITLE
run agent-integration-tests against T2 nightly

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/agent-integration-tests#7]
As of now, these integration tests have to be run manually on the devs' machines. 

We want to run them nightly w/ GitHub Actions and use T2 to generate a cluster that we run against.

- [x] Git checkout in Testdriver must be the same as current branch in this action!

**Comment by backstreetkiwi** [comment]
A basic version is running, although it is not very satisfactory:
The Test itself is not executed on the actual test runner but instead on one of the nodes of the cluster. This would be easier if we'd manage to join the VPN of the cluster with the build runner...

**Comment by backstreetkiwi** [comment]
It turns out that the team had a different view on this (and it's fine with me):

> A basic version is running, although it is not very satisfactory:
> The Test itself is not executed on the actual test runner but instead on one of the nodes of the cluster. This would be easier if we'd manage to join the VPN of the cluster with the build runner...

So we stick with testing through a dedicated test-runner inside the cluster but enhance this idea by (1) generating a reusable GitHub Action (step?) to use T2 and (2) add the test-driver node to the T2 templates as an option (new tasks required)

UPDATE: no custom GitHub Actions, we'll stick to Python instead, see https://github.com/stackabletech/t2/issues/45

**Comment by soenkeliebau** [comment]
I think this will come up again once we start looking into building out a proper test suite with reporting of what was tested when with which result etc.

For now this is good enough and serves our purpose.

**Comment by backstreetkiwi** [comment]
Two issues for T2 are created, we put this task in the freezer until we're done with them:
- https://github.com/stackabletech/t2/issues/44
- https://github.com/stackabletech/t2/issues/45
